### ISSUE TITLE
Various problems

### ISSUE THREAD

**Issue by Danielkonge** [amaanq/tree-sitter-luadoc#8]
(See update at the end) 

I just installed the luadoc parser today, and it does seem to work nicely for a lot of standard type documentation, but I have run in to quite a few weird cases. The following is a list of problems I noticed, but I am not sure if all of these come from problems that can be fixed in this parser? If someone points me towards the correct places to edit stuff to fix these problems, then I can try to make a pull request with fixes for some (all?) of these.

## Problem 1

There seems to be a problem with `['<some_string>']` in `@field` although this works fine in LuaLS:

With LSP:

<img width="425" alt="Screenshot 2023-11-14 at 22 52 44" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/81b6c2fc-eceb-4784-9ef1-40cfb4f040c4">

<img width="392" alt="Screenshot 2023-11-14 at 22 38 00" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/9458eac4-6ef1-43f9-847f-7a0c1415fb55">

Similarly, putting something like `[string]` instead of an actual string for the `@field` name also doesn't parse as expected:

<img width="264" alt="Screenshot 2023-11-14 at 22 38 47" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/fb759eaf-b1df-4a77-8945-ea81224f7553">

<img width="394" alt="Screenshot 2023-11-14 at 22 39 26" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/3d1aad1a-53b5-44f5-b523-41c8d1384268">

Without LSP:

<img width="424" alt="Screenshot 2023-11-14 at 23 11 44" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/9a901afb-c607-414e-826d-72582c3339fc">

<img width="236" alt="Screenshot 2023-11-14 at 23 12 07" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/4eaaf54e-ca92-4994-9c95-737108851845">

I am not sure if a fix to one of these will help with the other, but they are at least pretty similar problems.

## Problem 2

Strings in `@alias` don't highlight as expected:

With LSP:

<img width="411" alt="Screenshot 2023-11-14 at 22 40 11" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/c953b9b1-bd49-4fc0-b05b-0789f182e2b9">

<img width="412" alt="Screenshot 2023-11-14 at 22 40 37" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/31817500-4f0f-45fa-a62c-f8f2ddd0941a">

<img width="428" alt="Screenshot 2023-11-14 at 23 02 21" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/16514939-198e-42a0-b5f7-69cc8dbda0e5">

Without LSP:

<img width="426" alt="Screenshot 2023-11-14 at 23 13 22" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/ff7d5c57-ad91-4e7d-bb8a-2f6731236c2d">

I would expect something like in `@field`:

<img width="450" alt="Screenshot 2023-11-14 at 22 41 16" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/99a7d41d-434f-4761-9c87-10e351ed36fa">

## Problem 3

Some problems are not obvious unless you turn off the LSP, e.g. a named return value to a type function is not captured correctly.

With LSP:

<img width="474" alt="Screenshot 2023-11-14 at 22 41 55" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/01805f7c-e2ca-458b-af59-5b4db35930a5">

Without LSP:

<img width="466" alt="Screenshot 2023-11-14 at 23 04 59" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/3ffa4cd0-495b-4449-bae5-1061a352d33b">

<img width="384" alt="Screenshot 2023-11-14 at 22 42 11" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/c64646a8-b103-4f2c-a9d5-3abd19f1ea27">

## Problem 4

`public`, `private` and `protected` seem to work as expected, but not `package`. 

With LSP:

<img width="294" alt="Screenshot 2023-11-14 at 22 43 34" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/bd9aa8ac-b5bd-4a81-a1a3-3d8bab333a7f">

<img width="378" alt="Screenshot 2023-11-14 at 22 43 54" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/c0605619-8b13-42c8-a12a-0f9ea7e7b21b">

Without LSP:

<img width="295" alt="Screenshot 2023-11-14 at 23 15 07" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/7f7e2992-5020-4701-864e-616a18912ad8">

The expected behavior is like `private` without LSP here:

<img width="289" alt="Screenshot 2023-11-14 at 23 19 46" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/0a22a8d0-a632-479c-82fb-3ddc79367d02">

## Problem 5

Something is wrong with adding a comment using `#` after the type descriptions end in `@param`, which I think is a pretty common way of writing (not sure about this though).

With LSP:

<img width="361" alt="Screenshot 2023-11-14 at 22 45 43" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/45fd872b-4968-41f4-be8f-0604bab00a11">

<img width="384" alt="Screenshot 2023-11-14 at 22 45 59" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/f4cd036e-fe69-4e3b-8f8a-7bf839fb52a4">

Without LSP:

<img width="365" alt="Screenshot 2023-11-14 at 23 23 28" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/d92c8ad2-f962-4a20-8a4e-1a3c2e136485">

## Problem 6

`@as` statements are not captured properly. 

With LSP:

<img width="305" alt="Screenshot 2023-11-14 at 22 46 53" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/c61e4288-2c5a-4003-aea0-6a4130b07a35">

<img width="408" alt="Screenshot 2023-11-14 at 22 47 21" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/0840f0f9-e0e7-4023-ac8f-d7a807557a58">

Without LSP:

<img width="415" alt="Screenshot 2023-11-14 at 23 21 54" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/0cc96b8b-e9c7-4593-bc71-9cbd6357ebbc">

## Sidenote / Problem 7

As a counterpoint to the above, sometimes the LSP makes the highlighting worse. It would be nice to be able to have this be the main highlighting.

With LSP:

<img width="867" alt="Screenshot 2023-11-14 at 22 42 52" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/99d8d2f8-7801-48c5-b999-5cd42391a1e0">

Without LSP:

<img width="847" alt="Screenshot 2023-11-14 at 23 09 14" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/9c9a5ea9-86d4-4710-9592-56b7d109775c">

<img width="386" alt="Screenshot 2023-11-14 at 22 43 17" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/57c4b2cc-f7a7-42f9-85e3-e2a1efa9608b">

But I think this might actually be me who writes the type wrong here, since more parentheses fix it for the LSP:

With LSP:

<img width="872" alt="Screenshot 2023-11-15 at 00 08 11" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/619061dd-00a5-4b2a-933e-32ee2f0b6919">

Without LSP:

<img width="878" alt="Screenshot 2023-11-15 at 00 08 53" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/1858a0f0-6e07-42b7-8e8e-300d97365920">

<img width="385" alt="Screenshot 2023-11-15 at 00 09 47" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/18b88fd7-7f18-4168-98f1-dde36c7cad21">

But now the parentheses aren't captured correctly by treesitter for the outer parentheses (where the red one matches the gray one - they would both be red if it matched correctly).

As mentioned above, I can try to fix some or all of these myself, if someone can point me in the right direction. 

## Question/Problem

Is there any way we could change the `(union_type)` to not be as "nested" as it currently is? Or is it easier to keep it the current way because of something to do with treesitter?

(Update: Is this only meant to provide highlighting for EmmyLua and not LuaLS? If so, I think a lot of my comments aren't relevant.)

**Comment by wookayin** [comment]
Hi! Those are all good points but I would appreciate it if you separate this into multiple independent issues so that they can be better tracked.

**Comment by Danielkonge** [comment]
> Hi! Those are all good points but I would appreciate it if you separate this into multiple independent issues so that they can be better tracked.

I don't mind splitting this out into multiple issues, but I was hoping to hear back from @amaanq first, especially I would like to know a bit more about this parser. I am still not sure if it is only meant to cover EmmyLua types, or if it should work with all the [LuaLS annotations](https://luals.github.io/wiki/annotations/)? 

Therefore I don't yet know which of the above are actually relevant, since I think some of the above are not actually wrong behavior, if this is only meant to be for EmmyLua types (I have never really looked too much into the difference, and have only been using LuaLS myself). 

Also, I can probably make pull requests fixing at least a few of these myself, but again I would like to be sure that my fixes would be relevant before doing that.

**Comment by amaanq** [comment]
I've fixed 1, 3, 4, 5, and 6.

For 2, it spans multiple comments so i don't think that's really doable, unless we assume comments starting with a | are continuations of an alias

7 is LSP related, so not considering that as an issue

I'm gonna close this as fixed, but let me know what you think about 2

**Comment by Danielkonge** [comment]
> I've fixed 1, 3, 4, 5, and 6.

Thank you, I will try out the updated parser and report back if I notice any problems.

> For 2, it spans multiple comments so i don't think that's really doable, unless we assume comments starting with a | are continuations of an alias
> ...
> I'm gonna close this as fixed, but let me know what you think about 2

Comments starting with `|` can also be used for `param` like these examples
```lua
---@param mode string
---|"'immediate'"  # comment 1
---|"'async'" # comment 2
function bar(mode) end
```
or
```lua
local A = 0
local B = 1

---@param active integer
---| `A` # Has a value of 0
---| `B` # Has a value of 1
function set(active) end
```
from https://luals.github.io/wiki/annotations/. I think it only shows up for `param` and `alias` though, and the use seems to be very similar. I don't really know enough about the parser to be able to say if there is a good solution here. If you can make some assumptions about lines starting with `---|`, I think it would be nice to at least be able to get some highlighting. Even if the parsed tree might not look that nice.

> 7 is LSP related, so not considering that as an issue

I mostly agree, but there did seem to be a problem with parsing the extra parentheses here:

Without LSP:

<img width="878" alt="Screenshot 2023-11-15 at 00 08 53" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/1858a0f0-6e07-42b7-8e8e-300d97365920">

<img width="385" alt="Screenshot 2023-11-15 at 00 09 47" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/18b88fd7-7f18-4168-98f1-dde36c7cad21">

It would be nice if that could be fixed, since that allows me to keep the LSP highlighting on for those cases without looking broken. (This is less important than the the fixed problems though.)

Once again, thank you for fixing all the other problems!

**Comment by amaanq** [comment]
ah yeah i didn't notice it was a tuple type - they're both fixed now (I added the | <type> ... construct as a continuation)

**Comment by Danielkonge** [comment]
> ah yeah i didn't notice it was a tuple type - they're both fixed now (I added the | ... construct as a continuation)

Thanks!

**Comment by Danielkonge** [comment]
<img width="788" alt="Screenshot 2024-01-25 at 22 41 39" src="https://github.com/amaanq/tree-sitter-luadoc/assets/7075380/ab8e2063-a18b-4cbf-9bd3-06b2273bd885">

I have tested the updated parser now, and I think everything other than `---|` works as expected. But I still don't get correct highlighting or parsing of the multiline `alias` (at least based on what I thought you added?).

**Comment by amaanq** [comment]
ah, luadoc is injected based on the prefix of the comment, | isn't accounted for. I'll PR a fix for that

**Comment by Danielkonge** [comment]
> ah, luadoc is injected based on the prefix of the comment, | isn't accounted for. I'll PR a fix for that

The linked pull request fixed the highlighting. Now everything seems to work. Thank you!
